name: Build app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn export

      - name: Upload Nightly Build
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: coyote-nightly
          path: build/libs/Skript-nightly.jar